name: Commitlint

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: read
  pull-requests: read

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Lint PR commits and title
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: commitlint.config.cjs
